version: "3.8"

services:
  app:
    image: hermesn/convertissor_worker:latest
    container_name: worker_container
    depends_on:
      - db
    environment:
      - DATABASE_HOST=mysql_db_worker
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=file_convert
    ports:
      - "5700:5000"

    networks:
      - my_network
    command: python /app/worker.py

  db:
    image: mysql:8.0
    container_name: mysql_db_worker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: file_convert
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3316:3306"
    networks:
      - my_network
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  my_network:
    external: true
